### ISSUE TITLE
.main-hero-paragraph marginida xatolik bor

### ISSUE THREAD

**Issue by akramjonnuriddinov** [MIRZOULUGBEK9008/CoffeeRoasters#1]
![image](https://user-images.githubusercontent.com/99048411/161523859-6c134449-a656-41bb-88b0-8c0c445fdc30.png)
Marginni tepasidagini o'chirish kerak.

**Comment by MIRZOULUGBEK9008** [comment]
Bratan to'g'rilab qo'ydim...
