### ISSUE TITLE
`.hero-two-main-paragraph` ning opacityini berish kerak.

### ISSUE THREAD

**Issue by akramjonnuriddinov** [MIRZOULUGBEK9008/CoffeeRoasters#3]
Shu textga `opacity: 0.8` berish kerak.

**Comment by MIRZOULUGBEK9008** [comment]
![image](https://user-images.githubusercontent.com/99461357/161659273-72d107c6-3405-4ba2-8fb2-c1dabee1b9c2.png)
 No comment !
